const tripImages = import.meta.glob('../assets/trips/*.jpg', {
  eager: true,
  import: 'default',
})

const LOCAL = (file) => tripImages[`../assets/trips/${file}.jpg`]

// Real landscape photos bundled via Vite (see scripts/download-trip-images.mjs)
export const TRIP_META = {
  'הבנייאס': {
    image: LOCAL('banias'),
    tagline: 'מפלים, נחלים ויער ירוק בגליל העליון',
    keywords: ['מפל', 'מים', 'נחל', 'גליל', 'צפון', 'טבע'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.8,
    baseReviews: 24,
  },
  'נחל דוד - עין גדי': {
    image: LOCAL('ein-gedi'),
    tagline: 'מעיינות מדבריים ונוף מרהיב על ים המלח',
    keywords: ['מעיין', 'מדבר', 'ים המלח', 'נחל', 'תצפית', 'דרום'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.9,
    baseReviews: 31,
  },
  'מכתש רמון': {
    image: LOCAL('ramon'),
    tagline: 'מכתש ענקי, שקיעות ושמי כוכבים',
    keywords: ['מכתש', 'נגב', 'שקיעה', 'כוכבים', 'תצפית', 'מדבר'],
    strollerFriendly: false,
    kidFriendly: false,
    familyFriendly: false,
    baseRating: 4.7,
    baseReviews: 19,
  },
  'מצדה - שביל הנחש': {
    image: LOCAL('masada'),
    tagline: 'עלייה תלולה לתצפית היסטורית מרהיבה',
    keywords: ['מצדה', 'היסטוריה', 'תצפית', 'שביל', 'דרום', 'זריחה'],
    strollerFriendly: false,
    kidFriendly: false,
    familyFriendly: false,
    baseRating: 4.6,
    baseReviews: 22,
  },
  'הר מירון': {
    image: LOCAL('meron'),
    tagline: 'פסגות, אוויר צלול ויער אורן',
    keywords: ['הר', 'פסגה', 'יער', 'גליל', 'צפון', 'טיול'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.5,
    baseReviews: 14,
  },
  'שמורת החולה': {
    image: LOCAL('hula'),
    tagline: 'אגמים, ציפורים ושבילי טבע רגועים',
    keywords: ['ציפורים', 'אגם', 'שמורה', 'משפחה', 'צפון', 'טבע'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.7,
    baseReviews: 18,
  },
  'נחל יהודייה - רמת הגולן': {
    image: LOCAL('yehudiya'),
    tagline: 'קניונים, מים קרים וקפיצות לבריכות',
    keywords: ['קניון', 'מים', 'גולן', 'קפיצה', 'מפל', 'צפון'],
    strollerFriendly: false,
    kidFriendly: false,
    familyFriendly: false,
    baseRating: 4.9,
    baseReviews: 27,
  },
  'חוף הבונים': {
    image: LOCAL('habonim'),
    tagline: 'חוף ים, סלעים ושקיעה על הים התיכון',
    keywords: ['חוף', 'ים', 'שקיעה', 'מרכז', 'קיץ', 'משפחה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.4,
    baseReviews: 16,
  },
  'פארק הירקון - תל אביב': {
    image: LOCAL('yarkon'),
    tagline: 'שבילים ירוקים, אופניים ופיקניק',
    keywords: ['פארק', 'אופניים', 'פיקניק', 'ירקון', 'תל אביב', 'מרכז'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.3,
    baseReviews: 20,
  },
  'תל דן': {
    image: LOCAL('tel-dan'),
    tagline: 'מעיינות, נחל וצמחייה עבותה בגליל',
    keywords: ['מעיין', 'נחל', 'גליל', 'צפון', 'מים', 'טבע'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.6,
    baseReviews: 17,
  },
  'נחל משושים': {
    image: LOCAL('meshushim'),
    tagline: 'בריכות טבעיות וקפיצות למים בגליל העליון',
    keywords: ['נחל', 'מים', 'קפיצה', 'גליל', 'צפון', 'קיץ'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.8,
    baseReviews: 21,
  },
  'תמנע - ערבה': {
    image: LOCAL('timna'),
    tagline: 'מכרה נחושת עתיק, עמודי שלמה ונוף מדברי',
    keywords: ['מדבר', 'ערבה', 'דרום', 'היסטוריה', 'תצפית', 'נגב'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.5,
    baseReviews: 15,
  },
  'גן לאומי בית גוברין': {
    image: LOCAL('beit-guvrin'),
    tagline: 'מערות, ארכיאולוגיה ושבילי טיול בין הכפרים',
    keywords: ['מערות', 'ארכיאולוגיה', 'דרום', 'שמורה', 'היסטוריה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.4,
    baseReviews: 13,
  },
  'נחל דרגה': {
    image: LOCAL('darga'),
    tagline: 'קניון תלול, מפלים ומסלול אתגרי בגליל',
    keywords: ['קניון', 'מפל', 'גליל', 'צפון', 'קשה', 'מים'],
    strollerFriendly: false,
    kidFriendly: false,
    familyFriendly: false,
    baseRating: 4.7,
    baseReviews: 19,
  },
  'קיסריה - שביל החוף': {
    image: LOCAL('caesarea'),
    tagline: 'חוף, שרידים עתיקים וטיילת על הים',
    keywords: ['חוף', 'ים', 'היסטוריה', 'מרכז', 'קיסריה', 'שקיעה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.5,
    baseReviews: 18,
  },
  'נחל שניר': {
    image: LOCAL('snir'),
    tagline: 'יער צפוף, מים זורמים ושביל מוצל',
    keywords: ['נחל', 'מים', 'גליל', 'צפון', 'יער', 'משפחה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.6,
    baseReviews: 16,
  },
  'הר תבור': {
    image: LOCAL('tavor'),
    tagline: 'עלייה לפסגה עם נוף מרהיב על הגליל',
    keywords: ['הר', 'פסגה', 'גליל', 'צפון', 'תצפית', 'טיול'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.5,
    baseReviews: 14,
  },
  'מצפה רמון': {
    image: LOCAL('mitzpe-ramon'),
    tagline: 'תצפית על מכתש רמון — אחד הנופים היפים בישראל',
    keywords: ['מכתש', 'תצפית', 'נגב', 'שקיעה', 'מדבר', 'רמון'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.9,
    baseReviews: 26,
  },
  'עין בוקק': {
    image: LOCAL('ein-bokek'),
    tagline: 'מעיינות חמים, מרחצאות ונוף על ים המלח',
    keywords: ['מעיין', 'ים המלח', 'דרום', 'מרחצאות', 'מדבר', 'רגיעה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.4,
    baseReviews: 12,
  },
  'חוף דור': {
    image: LOCAL('dor'),
    tagline: 'חול לבן, גלים ורוח ים בחוף הכרמל',
    keywords: ['חוף', 'ים', 'כרמל', 'מרכז', 'קיץ', 'גלים'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.3,
    baseReviews: 15,
  },
  'נחל עיון': {
    image: LOCAL('ayun'),
    tagline: 'מפלים מרהיבים ושביל לאורך הנחל בגליל העליון',
    keywords: ['מפל', 'נחל', 'גליל', 'צפון', 'מים', 'טבע'],
    strollerFriendly: false,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.7,
    baseReviews: 20,
  },
  'ציפורi העתיקה': {
    image: LOCAL('zippori'),
    tagline: 'פסיפסים ושרידים מהתקופה הרומית',
    keywords: ['ארכיאולוגיה', 'היסטוריה', 'גליל', 'צפון', 'עתיקות'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.4,
    baseReviews: 11,
  },
  'נחל הזורעים': {
    image: LOCAL('hazoreim'),
    tagline: 'מסלול מים קליל ליד הכינרת',
    keywords: ['נחל', 'כינרת', 'צפון', 'מים', 'קיץ', 'משפחה'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.5,
    baseReviews: 13,
  },
  'עתיקות בית שאן': {
    image: LOCAL('beit-shean'),
    tagline: 'תיאטרון רומי, עמודים ועיר עתיקה מרשימה',
    keywords: ['ארכיאולוגיה', 'היסטוריה', 'צפון', 'עמק', 'תיאטרון'],
    strollerFriendly: true,
    kidFriendly: true,
    familyFriendly: true,
    baseRating: 4.6,
    baseReviews: 17,
  },
}

const AREA_FALLBACK = {
  צפון: LOCAL('yehudiya'),
  דרום: LOCAL('ramon'),
  נגב: LOCAL('mitzpe-ramon'),
  מרכז: LOCAL('yarkon'),
}

export function getTripMeta(trip) {
  const name = trip?.nameTraveler || ''
  if (TRIP_META[name]) return TRIP_META[name]
  return {
    image: AREA_FALLBACK[trip?.area] || LOCAL('ramon'),
    tagline: `מסלול טיול באזור ${trip?.area || 'ישראל'}`,
    keywords: [trip?.area, trip?.difficultyLevel].filter(Boolean),
    baseRating: 4.0,
    baseReviews: 5,
  }
}

// Hero slideshow — unique trip photos, rotates on the home page
export const HERO_SLIDES = [
  ...new Set(Object.values(TRIP_META).map((m) => m.image).filter(Boolean)),
]
